### PR TITLE
Add port

### LINKED ISSUE #5: ssh-keyscan should accept a port parameter
My server runs on a non-standard port number, so `ssh-keyscan` will fail. There should be a parameter for that.

### PR DESCRIPTION
**Pull request by ksqsf**
Closes #5

### CODE REVIEW

**Review by kielabokkie — APPROVED** [review]

**Comment by kielabokkie** [comment]
Thanks for this PR @ksqsf, it's a nice addition 👍

**Comment by kielabokkie** [comment]
@ksqsf Your PR actually had a small bug (see [my PR](https://github.com/kielabokkie/ssh-key-and-known-hosts-action/pull/7/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L11)).

I've just tagged v1.1.0. Can you please check if it's all working ok for you now and let me know?

**Comment by ksqsf** [comment]
@kielabokkie Oops, my bad! The fixed version is working fine for me.

**Comment by kielabokkie** [comment]
@ksqsf No worries, happy to know it's working fine :)

**Pull request merged**
